spring:
  config:
    import: "optional:configserver:"
  application:
    name: "OnlineMovieStoreOrder"

eureka:
  client:
    healthcheck:
      enabled: false
server:
  port: 8081

OnlineMovieStoreOrder:
  server:
    customer:
      url: "http://localhost:8082/api/customer"
      ws:
        getCustomer: /customers/getCustomer

    inventory:
      url: "http://localhost:8080/api/inventory"
      ws:
        getMovie: /movies/getMovie
        updateMovie: /movies/updateMovie

    payment:
      url: "http://localhost:8084/api/payment"
      ws:
        getCustomer: /customers/getCustomer

    delivery:
      url: "http://localhost:8085/api/delivery"
      ws:
        processDelivery: /deliveries/processDelivery